version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTPSERVER_PORT}:${HTTPSERVER_PORT}"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - fullstack
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes: 
     - postgres:/var/lib/postgresql/data
    networks:
      - fullstack  

volumes:
  app:
  postgres:  

networks:
  fullstack:
    driver: bridge